services:
  ia_pause:
    hostname:         ia_pause.innovanon.com
    build:
      context:        .
      tags:
        - innovanon/ia_pause:latest
        -           ia_pause:latest
        - innovanon/ia_pause
        -           ia_pause
    image:            innovanon/ia_pause
    restart:          no
    logging:
      driver:         syslog   
